collector:
  replicaCount: 1
  googleCloud:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

prometheus:
  server:
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    retention: 1d
    persistentVolume:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
  alertmanager:
    enabled: true
    persistence:
      enabled: false
  nodeExporter:
    enabled: false

grafana:
  persistence:
    enabled: false

jaeger:
  allInOne:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 384Mi
