apiVersion: v1
kind: Secret
metadata:
  name: data-service-db-credentials
  labels:
    app.kubernetes.io/name: {{ include "data-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  cloud_sql_dsn: ""
  aws_rds_dsn: ""
