apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: data-service
  labels:
    istio-injection: enabled
